#!/usr/bin/env bash
set -euo pipefail

GATEWAY_URL="${GATEWAY_URL:-http://localhost:8080}"

curl -sS -X POST "$GATEWAY_URL/api/transactions" \
  -H "Content-Type: application/json" \
  -d '{
    "customerId": "11111111-1111-1111-1111-111111111111",
    "sourceAccountId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "destinationAccountId": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    "amount": 15000.00,
    "currency": "EUR",
    "transactionType": "TRANSFER",
    "channel": "SWIFT",
    "originCountry": "FR",
    "destinationCountry": "AE",
    "reference": "Large cross-border transfer generated by demo script",
    "executedAt": "2026-06-05T12:00:00Z"
  }' | python -m json.tool

echo
echo "Wait a few seconds, then open the dashboard or run:"
echo "curl $GATEWAY_URL/api/alerts"
echo "curl $GATEWAY_URL/api/cases"
